"""Test migration

Revision ID: 112d6e7e57b9
Revises:
Create Date: 2026-04-06 15:37:15.691538

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "112d6e7e57b9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
