"""added relationships to models

Revision ID: 844c62422511
Revises: 6c5f3faf9f33
Create Date: 2026-04-07 16:09:35.785516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "844c62422511"
down_revision: Union[str, Sequence[str], None] = "6c5f3faf9f33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("user_fk", sa.Uuid(), nullable=False))
    op.add_column("comment", sa.Column("listing_fk", sa.Uuid(), nullable=False))
    op.drop_constraint(op.f("comment_author_id_fkey"), "comment", type_="foreignkey")
    op.drop_constraint(op.f("comment_listing_id_fkey"), "comment", type_="foreignkey")
    op.create_foreign_key(None, "comment", "user", ["user_fk"], ["id"])
    op.create_foreign_key(None, "comment", "listing", ["listing_fk"], ["id"])
    op.drop_column("comment", "listing_id")
    op.drop_column("comment", "author_id")
    op.add_column("message", sa.Column("sender_fk", sa.Uuid(), nullable=False))
    op.add_column("message", sa.Column("receiver_fk", sa.Uuid(), nullable=False))
    op.drop_constraint(op.f("message_receiver_id_fkey"), "message", type_="foreignkey")
    op.drop_constraint(op.f("message_sender_id_fkey"), "message", type_="foreignkey")
    op.create_foreign_key(None, "message", "user", ["sender_fk"], ["id"])
    op.create_foreign_key(None, "message", "user", ["receiver_fk"], ["id"])
    op.drop_column("message", "sender_id")
    op.drop_column("message", "receiver_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("receiver_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "message",
        sa.Column("sender_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        op.f("message_sender_id_fkey"), "message", "user", ["sender_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("message_receiver_id_fkey"), "message", "user", ["receiver_id"], ["id"]
    )
    op.drop_column("message", "receiver_fk")
    op.drop_column("message", "sender_fk")
    op.add_column(
        "comment",
        sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "comment",
        sa.Column("listing_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.create_foreign_key(
        op.f("comment_listing_id_fkey"), "comment", "listing", ["listing_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("comment_author_id_fkey"), "comment", "user", ["author_id"], ["id"]
    )
    op.drop_column("comment", "listing_fk")
    op.drop_column("comment", "user_fk")
    # ### end Alembic commands ###
