"""added keycloak id in user

Revision ID: 8bacbd73f936
Revises: 844c62422511
Create Date: 2026-04-14 15:37:12.621737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bacbd73f936"
down_revision: Union[str, Sequence[str], None] = "844c62422511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    op.drop_table("message")
    op.drop_table("listing")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "full_name", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name=op.f("user_created_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["user.id"], name=op.f("user_updated_by_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "listing",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_fk", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "manufacturer", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("model", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "kilometers",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_fk"], ["user.id"], name=op.f("listing_user_fk_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("listing_pkey")),
    )
    op.create_table(
        "message",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_read", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("sender_fk", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("receiver_fk", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name=op.f("message_created_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["receiver_fk"], ["user.id"], name=op.f("message_receiver_fk_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["sender_fk"], ["user.id"], name=op.f("message_sender_fk_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["user.id"], name=op.f("message_updated_by_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("message_pkey")),
    )
    op.create_table(
        "comment",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "content", sa.VARCHAR(length=250), autoincrement=False, nullable=False
        ),
        sa.Column("user_fk", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("listing_fk", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name=op.f("comment_created_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["listing_fk"], ["listing.id"], name=op.f("comment_listing_fk_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["user.id"], name=op.f("comment_updated_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_fk"], ["user.id"], name=op.f("comment_user_fk_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("comment_pkey")),
    )
    # ### end Alembic commands ###
