"""Added auditable columns

Revision ID: 21506e132214
Revises: adf91dc1186e
Create Date: 2026-04-06 16:41:27.142561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21506e132214'
down_revision: Union[str, Sequence[str], None] = 'adf91dc1186e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'user', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'updated_by')
    op.drop_column('user', 'created_by')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
