from typing import List, Protocol, TypeVar
from uuid import UUID

T = TypeVar("T")


class BaseRepositoryProtocol(Protocol[T]):
    async def find_all(self) -> List[T]: ...

    async def find_by(self, obj_id: UUID) -> T | None: ...

    async def create(self, model: T) -> T: ...

    async def update(self, obj_id: UUID, update_data: dict) -> T | None: ...

    async def delete_by_id(self, obj_id: UUID) -> bool: ...
